// Mocks generated by Mockito 5.4.6 from annotations
// in study_app/test/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:study_app/core/config/base_response/result.dart' as _i5;
import 'package:study_app/features/home/domain/entities/categories_entity.dart'
    as _i9;
import 'package:study_app/features/home/domain/entities/products_entity.dart'
    as _i6;
import 'package:study_app/features/home/domain/repositories/home_repositories.dart'
    as _i2;
import 'package:study_app/features/home/domain/use_cases/get_categories_use_case.dart'
    as _i8;
import 'package:study_app/features/home/domain/use_cases/get_products_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepositories_0 extends _i1.SmartFake
    implements _i2.HomeRepositories {
  _FakeHomeRepositories_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsUseCase extends _i1.Mock
    implements _i3.GetProductsUseCase {
  MockGetProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepositories get homeRepositories =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepositories),
            returnValue: _FakeHomeRepositories_0(
              this,
              Invocation.getter(#homeRepositories),
            ),
          )
          as _i2.HomeRepositories);

  @override
  _i4.Future<_i5.Result<List<_i6.ProductsEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<List<_i6.ProductsEntity>>>.value(
              _i7.dummyValue<_i5.Result<List<_i6.ProductsEntity>>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<List<_i6.ProductsEntity>>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i8.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepositories get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepositories_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepositories);

  @override
  _i4.Future<_i5.Result<List<_i9.CategoriesEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Result<List<_i9.CategoriesEntity>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i9.CategoriesEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i9.CategoriesEntity>>>);
}
